export const Icons = {
    activeHome: require('./activeHome.png'),
    activeSearch: require('./activeSearch.png'),
    activeLike: require('./activeLike.png'),
    activeSetting: require('./activeSetting.png'),
    inactiveHome: require('./inactiveHome.png'),
    inactiveSearch: require('./inactiveSearch.png'),
    inactiveLike: require('./inactiveLike.png'),
    inactiveSetting: require('./inactiveSetting.png'),
    arrowIcon: require('./arrowIcon.png'),
    bibleLogoIcon: require('./bibbleLogoIcon.png'),
    bookIcon: require('./bookIcon.png'),
    coursalIcon1: require('./coursalIcon1.png'),
    coursalIcon2: require('./coursalIcon2.png'),
    backIcon: require('./backIcon.png'),
    copyIcon: require('./copyIcon.png'),
    heartIcon: require('./heartIcon.png'),
    browserIcon: require('./browserIcon.png'),
    shareIcon: require('./shareIcon.png'),
    crownIcon: require('./crownIcon.png'),
    bibbleOutlineIcon: require('./bibbleOutlineIcon.png'),
    rythemIcon: require('./rythemIcon.png'),
}